version: "3"

services:
  db:
    image: postgres:14-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=visits
volumes:
  pg_data:
